name: drlnd
channels:
  - defaults
dependencies:
  - python=3.6.13
  - pip=21.2.2
  - pip:
    - box2d-py==2.3.5
    - dataclasses==0.8
    - gym==0.21.0
    - hydra-core==1.1.1
    - matplotlib==3.3.4
    - numpy==1.19.5
    - unityagents==0.4.0
    - pre-commit==2.17.0
